name: workflow-conclusion-action
description: GitHub action to get workflow conclusion.
branding:
  icon: thermometer
  color: blue

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: false

outputs:
  conclusion:
    description: Workflow conclusion

runs:
  using: node20
  main: ./dist/index.js
